all : RangeRunner.class Runner.class Sum.class ThreadMultiSum.class ThreadSum.class SumTask.class DateServer.class DateClient.class

clean :
	-rm *.class 2> /dev/null

RangeRunner.class : RangeRunner.java
	javac RangeRunner.java

Runner.class : Runner.java
	javac Runner.java

Sum.class : Sum.java
	javac Sum.java

ThreadMultiSum.class : ThreadMultiSum.java
	javac ThreadMultiSum.java

ThreadSum.class : ThreadSum.java
	javac ThreadSum.java

SumTask.class : SumTask.java
	javac SumTask.java

DateClient.class : DateClient.java
	javac DateClient.java

DateServer.class : DateServer.java
	javac DateServer.java
